name: Test Conectividad EC2

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  connectivity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test ping a EC2
        run: |
          echo "Probando conectividad ICMP (ping) a la instancia EC2..."
          ping -c 4 ${{ secrets.EC2_DNS }} || echo "Ping falló"

      - name: Test puerto SSH (22)
        run: |
          echo "Probando puerto SSH 22 con nc..."
          nc -vz -w 5 ${{ secrets.EC2_DNS }} 22 || echo "Conexión al puerto 22 falló"

      - name: Test puertos de la aplicación (8081)
        run: |
          echo "Probando puerto 8081 de la app..."
          nc -vz -w 5 ${{ secrets.EC2_DNS }} 8081 || echo "Conexión al puerto 8081 falló"
