name: Test SSH Conexión EC2

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio (necesario para el workspace)
      - uses: actions/checkout@v3

      # 2️⃣ Probar conexión SSH
      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_DNS }}        # DNS público de tu EC2
          username: ec2-user                  # Usuario correcto para Amazon Linux 2023
          key: ${{ secrets.EC2_KEY }}        # Contenido completo del .pem
          port: 22
          script: |
            echo "Conexión SSH exitosa desde GitHub Actions"
            whoami
            hostname
