name: Test EC2 Deployment Setup

on:
  push:
    branches:
      - main

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    env:
      CHANGED_PROJECTS: "Clientes Inventarios modulo-jwt paquetes Servicios"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Configure Java environment
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Java version
        run: java -version

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_DNS }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_DNS }} "echo 'SSH connection OK'"

      - name: Build projects
        run: |
          for proj in $CHANGED_PROJECTS; do
            echo "=== Building $proj ==="
            cd $proj
            if [ -f "pom.xml" ]; then
              mvn clean package -DskipTests -Dmaven.compiler.release=21
            elif [ -f "build.gradle" ]; then
              ./gradlew build -x test
            fi
            cd ..
          done

      - name: List generated JARs
        run: |
          for proj in $CHANGED_PROJECTS; do
            echo "=== JARs for $proj ==="
            ls -l $proj/target/*.jar || ls -l $proj/build/libs/*.jar || echo "No JAR found for $proj"
          done
