name: Deploy JARs to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CHANGED_PROJECTS: "Clientes Inventarios modulo-jwt paquetes Servicios"
      START_PORT: 8080
      END_PORT: 8086

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_DNS }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_DNS }} "echo 'SSH connection successful'"

      - name: Configure EC2 Environment
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_DNS }} "
            # Disable firewall
            echo '=== Disabling firewall ==='
            sudo iptables -F 2>/dev/null || true
            sudo iptables -X 2>/dev/null || true
            sudo iptables -t nat -F 2>/dev/null || true
            sudo iptables -t nat -X 2>/dev/null || true
            sudo iptables -P INPUT ACCEPT 2>/dev/null || true
            sudo iptables -P FORWARD ACCEPT 2>/dev/null || true
            sudo iptables -P OUTPUT ACCEPT 2>/dev/null || true
            
            # Verify Java installation
            echo '=== Java Version ==='
            java -version || echo 'Java not found'
            
            # Create base directories
            echo '=== Creating directories ==='
            for proj in $CHANGED_PROJECTS; do
              mkdir -p /home/ec2-user/\$proj /home/ec2-user/\$proj/backup
            done
            
            echo 'EC2 environment configured'
          "

      - name: Build projects
        run: |
          for proj in $CHANGED_PROJECTS; do
            echo "=== Building $proj ==="
            if [ -d "$proj" ]; then
              cd "$proj"
              if [ -f "pom.xml" ]; then
                mvn clean package -DskipTests
              elif [ -f "build.gradle" ]; then
                chmod +x ./gradlew
                ./gradlew build -x test
              fi
              cd ..
            else
              echo "WARNING: Directory $proj not found"
            fi
          done

      - name: Verify JARs were built
        run: |
          echo "=== Verifying JAR files ==="
          for proj in $CHANGED_PROJECTS; do
            echo "Checking $proj..."
            if ls $proj/target/*.jar 1> /dev/null 2>&1; then
              echo "✓ Found JAR in target/: $(ls $proj/target/*.jar)"
            elif ls $proj/build/libs/*.jar 1> /dev/null 2>&1; then
              echo "✓ Found JAR in build/libs/: $(ls $proj/build/libs/*.jar)"
            else
              echo "❌ ERROR: No JAR file found for $proj"
              exit 1
            fi
          done

      - name: Deploy projects to EC2
        run: |
          set -e
          PORT=$START_PORT
          
          for proj in $CHANGED_PROJECTS; do
            echo "=== Deploying $proj on port $PORT ==="

            # Find JAR file
            JAR_FILE=""
            if ls $GITHUB_WORKSPACE/$proj/target/*.jar 1> /dev/null 2>&1; then
              JAR_FILE=$(ls $GITHUB_WORKSPACE/$proj/target/*.jar | head -1)
            elif ls $GITHUB_WORKSPACE/$proj/build/libs/*.jar 1> /dev/null 2>&1; then
              JAR_FILE=$(ls $GITHUB_WORKSPACE/$proj/build/libs/*.jar | head -1)
            fi

            if [ -z "$JAR_FILE" ]; then
              echo "ERROR: No JAR file found for $proj"
              exit 1
            fi

            echo "Deploying JAR: $JAR_FILE"

            # Create backup on EC2
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_DNS }} "
              mkdir -p /home/ec2-user/$proj /home/ec2-user/$proj/backup
              if ls /home/ec2-user/$proj/*.jar 1> /dev/null 2>&1; then
                echo 'Creating backup of existing JAR'
                mv /home/ec2-user/$proj/*.jar /home/ec2-user/$proj/backup/
              fi
            "

            # Upload new JAR
            scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "$JAR_FILE" ec2-user@${{ secrets.EC2_DNS }}:/home/ec2-user/$proj/

            # Deploy with health check
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_DNS }} "
              set -e
              cd /home/ec2-user/$proj
              
              # Stop existing process
              echo 'Stopping existing process...'
              pkill -f \"java.*$proj\" || true
              sleep 2
              
              # Kill any process using the port
              PORT_PID=\$(lsof -ti:$PORT 2>/dev/null || echo '')
              if [ ! -z \"\$PORT_PID\" ]; then
                echo \"Killing process \$PORT_PID using port $PORT\"
                kill -9 \$PORT_PID 2>/dev/null || true
                sleep 2
              fi
              
              # Start new application
              echo 'Starting application...'
              nohup java -jar *.jar --server.port=$PORT --server.address=0.0.0.0 > $proj.log 2>&1 &
              APP_PID=\$!
              echo \"Started with PID: \$APP_PID\"
              
              # Wait and check health
              sleep 20
              
              if ss -tuln | grep -q \":$PORT\"; then
                echo \"✅ $proj successfully started on port $PORT\"
                echo \"Application logs (last 5 lines):\"
                tail -5 $proj.log || echo 'No logs yet'
              else
                echo \"❌ $proj failed to start on port $PORT, performing rollback...\"
                kill \$APP_PID 2>/dev/null || true
                sleep 2
                
                if ls backup/*.jar 1> /dev/null 2>&1; then
                  echo 'Restoring backup...'
                  rm -f *.jar
                  mv backup/*.jar .
                  nohup java -jar *.jar --server.port=$PORT --server.address=0.0.0.0 > $proj.log 2>&1 &
                  sleep 15
                  
                  if ss -tuln | grep -q \":$PORT\"; then
                    echo \"✅ Rollback successful for $proj\"
                  else
                    echo \"❌ Rollback failed for $proj\"
                    echo \"Rollback logs:\"
                    tail -20 $proj.log
                  fi
                else
                  echo 'No backup available for rollback'
                  echo \"Application logs:\"
                  cat $proj.log
                fi
              fi
            " || echo "Deployment for $proj completed with warnings"

            # Increment port for next project
            PORT=$((PORT + 1))
            if [ $PORT -gt $END_PORT ]; then
              PORT=$START_PORT
            fi
            echo ""
          done

      - name: Final deployment verification
        run: |
          echo "=== Final deployment status ==="
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_DNS }} "
            echo '=== Running Java Processes ==='
            ps aux | grep java | grep -v grep || echo 'No Java processes found'
            
            echo ''
            echo '=== Open Ports ==='
            ss -tuln | grep 'LISTEN' | grep -E ':(808[0-6])' || echo 'No deployment ports found'
            
            echo ''
            echo '=== Application Status ==='
            for proj in $CHANGED_PROJECTS; do
              echo \"--- \$proj ---\"
              if [ -f \"/home/ec2-user/\$proj/\$proj.log\" ]; then
                echo 'Last 10 lines of log:'
                tail -10 \"/home/ec2-user/\$proj/\$proj.log\"
                echo ''
              else
                echo 'No log file found'
              fi
            done
            
            echo '=== System Resources ==='
            echo 'Disk usage:'
            df -h /home/ec2-user/
            echo ''
            echo 'Memory usage:'
            free -h
            echo ''
            echo 'Current time:'
            date
          "

      - name: Cleanup
        if: always()
        run: |
          echo "=== Cleanup ==="
          rm -f ~/.ssh/id_rsa
          echo "SSH key cleaned up"
