name: Despliegue a EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CHANGED_PROJECTS: "tu_proyecto"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar llave SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Test conexión SSH
      run: ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} -p 22 "echo Conexión exitosa"

    - name: Desplegar proyecto
      run: |
        for proj in $CHANGED_PROJECTS; do
          echo "=== Desplegando $proj ==="
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} -p 22 "
            mkdir -p /home/ec2-user/$proj
            mkdir -p /home/ec2-user/$proj/backup
            if ls /home/ec2-user/$proj/*.jar 1> /dev/null 2>&1; then
              mv /home/ec2-user/$proj/*.jar /home/ec2-user/$proj/backup/
            fi
          "
          scp -i ~/.ssh/id_rsa -P 22 $GITHUB_WORKSPACE/$proj/target/*.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/$proj/
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} -p 22 "
            pkill -f '$proj' || true
            nohup java -jar /home/ec2-user/$proj/*.jar > /home/ec2-user/$proj/$proj.log 2>&1 &
            sleep 10
          "
        done
